# compile producing an object file
compile:
	g++ -c HelloWorld.cpp
# link producing an impermitted executable file
link:
	g++ HelloWorld.o
# compile and link producing only an impermitted executable file
compile-link:
	g++ HelloWorld.cpp
# run the executable file
run:
	./a.out

# recommended building
build:
	g++ HelloWorld.cpp -o HelloWorld
runall:
	./HelloWorld

# clean object files and executable files
clean-o:
	rm HelloWorld.o 
clean-e:
	rm a.out
clean-runall:
	rm HelloWorld
